version: '2.4'
services:
  app:
    container_name: node
    image: node
    build:
      context: ./
      dockerfile: Dockerfile_loc
      args:
        buildno: 1
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    restart: always
    ports:
      - 3779:3779
    command: npm run start-watch
    mem_limit: 40840M
    cpu_shares: 73
    cpu_count: 2
    cpus: 0.5
